### ISSUE TITLE
Keys list in `encrypt` and `sign` dialogs are reverse

### ISSUE THREAD

**Issue by RZHSSNZDH** [konstantintutsch/Lock#38]
### Describe the bug …

In encryption dialog the app should list all keys which I have their public keys not only my keys. And also in sign dialog the app should list the keys I have their private keys, my own keys. The app's behavior is reverse. It lists my own keys in encryption dialog and does not show the keys which I have only their public keys and lists all of keys available in sign dialog even if I do not have their private keys. Then when I choose a key in sign dialog which I do not have its private key, the app shows `Signing failed` error.

### Which version of Lock are you using?

1.2.2

### Which version of GnuPG Made Easy is Lock using?

1.23.2

### Which distribution did this bug occur on?

Arch

### Source

Flathub

### Console Output (stdout)

```shell
** Message: 22:28:20.046: GnuPG Made Easy 1.23.2
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:752: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:783: FINISHME: support more multi-planar formats with DRM modifiers

** (com.konstantintutsch.Lock:2): WARNING **: 22:28:27.356: Failed to sign GPGME data from memory: Unusable secret key
```

### ~/.gnupg/gpg.conf

```shell
I do not have this file!
```

### ~/.gnupg/gpg-agent.conf

```shell
I do not have this too!
```

**Comment by konstantintutsch** [comment]
Please share a screenshot of both dialogs and the output of `gpg --list-keys`.

**Comment by RZHSSNZDH** [comment]
First one is encrypt and the second one is sign.
![image](https://github.com/user-attachments/assets/7d994868-09c3-4e12-a7b1-0fa1e3ef0627)
![image](https://github.com/user-attachments/assets/294fcdc2-d721-4d67-bd13-434b929e8957)
/home/reza/.gnupg/pubring.kbx
-----------------------------
pub   rsa3072 2023-10-07 [SC]
      9E92AD49ED36C413F6CA8E0076217ECB76C88661
uid           [ultimate] Reza Hosseinzadeh (For git) <rezahsnzdh@protonmail.com>

pub   ed25519 2021-10-24 [SC]
      5C4DE5DD4357E27F9EEE545F881F1BAD2D3F622F
uid           [ unknown] rezahsnzdh@protonmail.com <rezahsnzdh@protonmail.com>
sub   cv25519 2021-10-24 [E]

pub   rsa3072 2021-03-26 [SC] [expired: 2024-03-25]
      C2BA2B2512178294B83C55FF040A9E7D0064262B
uid           [ expired] Mostafa Ahangarha <ahangarha@riseup.net>

pub   rsa3072 2024-03-16 [SC]
      A96D5B03384DBA7F719170BA47718D151774717F
uid           [ unknown] Nesa Hosseinzadeh <ehrhnhthmk@gmail.com>
sub   rsa3072 2024-03-16 [E]

**Comment by RZHSSNZDH** [comment]
If I want to encrypt something with `C2BA2B2512178294B83C55FF040A9E7D0064262B` key I can't! It is not listed in encryption dialog.

**Comment by konstantintutsch** [comment]
That's because `C2BA2B2512178294B83C55FF040A9E7D0064262B` can not be used for encryption. It needs a key or subkey generated with an algorithm supporting encryption.

Let's take `5C4DE5DD4357E27F9EEE545F881F1BAD2D3F622F` for example:

1. `pub ed25519 2021-10-24 [SC]`: this line means that the root key is an ed25519 key and is capable of signing which is indicated by the `[SC]` at the end of the line
2. `sub cv25519 2021-10-24 [E]`: this line means that `5C4DE5DD4357E27F9EEE545F881F1BAD2D3F622F` has a cv25519 subkey that is encryption capable which is indicated by the `[E]` at the end of the line

If we now check `C2BA2B2512178294B83C55FF040A9E7D0064262B`, we see that it is only composed of a single key:

1. `pub rsa3072 2021-03-26 [SC] [expired: 2024-03-25]`: this key is not only a signing key (`[SC]`) but is also expired (`[expired: 2024-03-25]`)

---

Please understand the basics of public-key cryptography before reporting bugs to this project again.

**Comment by RZHSSNZDH** [comment]
`pub   rsa2048 2024-02-08 [SCEAR]
      8F3B7B6973C8D756B1F93561F9C9C616BB705F3A
uid           [ unknown] Magda <magda@airmail.cc>
sub   rsa2048 2024-02-08 [SEA]
`
This key is shown in sign diolog, but why when I choose it error `Signing failed` is appeared. If it is for signing why I get the error and if it is not for signing why it is listed in signing dialog?

**Comment by konstantintutsch** [comment]
Please create a new issue with all relevant information for this error.
